apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.container.frontEndName }}-ingress
  namespace: {{ .Values.container.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.certificate.certtype }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ .Values.certificate.appdnsname }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.certificate.appdnsname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.container.frontEndName }}-service
          servicePort: {{ .Values.container.frontEndServiceport }} 
        path: /(.*)