apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.container.namespace }}
spec:
  secretName: tls-secret
  dnsNames:
  - {{ .Values.certificate.appdnsname }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.certificate.appdnsname }}
  issuerRef:
    name: {{ .Values.certificate.certtype }}
    kind: ClusterIssuer