apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.daprbackEndName }}-service
  labels:
    app: {{ .Values.label.name }}
  namespace: {{ .Values.container.namespace }}
spec:
  selector:
    app: {{ .Values.container.daprbackEndName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.container.daprbackEndServiceport }}
      targetPort: {{ .Values.container.daprbackendport }}
